name: DanielJBurtART
favicon: null
layout_spectrum: 0.117643968667835
typography_spectrum: 0.0684179081581533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c2bfba'
    - '#33201b'
    - '#978d85'
    - '#6d6058'
    - '#030000'
  brandStrength: 0.3125
  lightness: 0.7108700945973396
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
