name: Daniel J Burt
favicon: null
layout_spectrum: 0.88716
typography_spectrum: 0.64105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#b7b6b4'
    - '#4c4b3a'
    - '#827870'
    - '#f45472'
  brandStrength: 0.3125
  lightness: 0.7108700945973396
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
