name: DanielJBurtART
favicon: null
layout_spectrum: 0.117643968667835
typography_spectrum: 0.0684179081581533
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3772533305454999
  lightness: 0.7108700945973396
  saturation: 0.931328505044803
  rhythmicContrast: 0.8986050612293184
purpose: []
