name: Daniel J Burt
favicon: null
layout_spectrum: 0.65787
typography_spectrum: 0.64105
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#131514'
    - '#fffeff'
    - '#b5ae9e'
    - '#a9e573'
    - '#817e79'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
